### ISSUE TITLE
next_migration_number

### ISSUE THREAD

**Issue by andrenth** [80beans/wysihat-engine#11]
Running "rails g wysihat" in rails 3 after installation gives me a NotImplementedError exception in the next_migration_number method. This method is defined under Rails::Generators::Migration::ClassMethods in the rails source, so changing it to be a class method in wysihat fixed it for me:

<pre>-def next_migration_number(dirname) #:nodoc:
+def self.next_migration_number(dirname) #:nodoc:</pre>

**Comment by blaines** [comment]
That also worked for me! Thanks!

**Comment by onesup** [comment]
.rvm/gems/ruby-1.9.2-head/gems/wysihat-engine-0.1.13/lib/generators/wysihat_generator.rb

**Comment by mrrooijen** [comment]
That fixed the generator for me as well! Thanks!

**Comment by slash4** [comment]
Fixed here too :)

**Comment by alantocheri** [comment]
I'm getting a similar error: 

/Users/Alan/.rvm/gems/ruby-1.8.7-p302/gems/railties-3.0.1/lib/rails/generators/migration.rb:50:in `migration_template': undefined method`next_migration_number' for WysihatGenerator:Class (NoMethodError)
from /Users/Alan/.rvm/gems/ruby-1.8.7-p302/gems/wysihat-engine-0.1.13/lib/generators/wysihat_generator.rb:60:in `install_wysihat'

I've tried editing .rvm/gems/ruby-1.8.7-p302/gems/railties-3.0.1/lib/rails/generators/migration with the fix (changes happen on line #29) and it doesn't seem to make a difference. 

Can I change the wysihat_generator.rb to fix it? I'm sure I'm doing something terribly wrong.

**Comment by stanislaw** [comment]
+1 to alantocheri

**Comment by stanislaw** [comment]
It seems, that commenting "raise NotImplementedError" in next_migration_number method solves issue.

Having it commented, all worked!

**Comment by alantocheri** [comment]
Although the error was coming from ruby-1.8.7-p302, I ended doing what stanislaw suggested in the /ruby-1.8.7-p302@rails3 directory. It must be a RVM thing. That seemed to 'work'. (thanks Stanislaw)

The issue now is that it created the migration file without a timestamp and rake seems to miss it. I just copied/pasted into a new migration - but wondering if there's a way to fix this problem and the generate issue for rails 3?
