### ISSUE TITLE
Wysihat Gem - Rails 3

### ISSUE THREAD

**Issue by MissingHandle** [80beans/wysihat-engine#16]
running 'rails generate wysihat' results in:

/gems/railties-3.0.0/lib/rails/generators/migration.rb:30:in `next_migration_number': NotImplementedError (NotImplementedError)
/gems/railties-3.0.0/lib/rails/generators/migration.rb:49:in`migration_template'
/gems/wysihat-engine-0.1.13/lib/generators/wysihat_generator.rb:60:in `install_wysihat'
/gems/thor-0.14.1/lib/thor/task.rb:22:in`send'
/gems/thor-0.14.1/lib/thor/task.rb:22:in `run'
/gems/thor-0.14.1/lib/thor/invocation.rb:118:in`invoke_task'
/gems/thor-0.14.1/lib/thor/invocation.rb:124:in `invoke_all'
/gems/thor-0.14.1/lib/thor/shell.rb:14:in`map'
/gems/thor-0.14.1/lib/thor/core_ext/ordered_hash.rb:73:in `each'
/gems/thor-0.14.1/lib/thor/invocation.rb:124:in`map'
/gems/thor-0.14.1/lib/thor/invocation.rb:124:in `invoke_all'
/gems/thor-0.14.1/lib/thor/group.rb:226:in`dispatch'
/gems/thor-0.14.1/lib/thor/base.rb:389:in `start'
/gems/railties-3.0.0/lib/rails/generators.rb:163:in`invoke'
/gems/railties-3.0.0/lib/rails/commands/generate.rb:10
/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:239:in `require'
/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:239:in`require'
/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:225:in `load_dependency'
/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:591:in`new_constants_in'
/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:225:in `load_dependency'
/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:239:in`require'
/gems/railties-3.0.0/lib/rails/commands.rb:17
    from script/rails:6:in `require'
    from script/rails:6

would love to help, but pretty sure I don't know enough about rails 3 or wysihat-engine to do so...

**Comment by MissingHandle** [comment]
addressed by the "next_migration_number" Post
